site_name: Nagasaka備忘録
site_url: https://example.com/
repo_url: https://github.com/NagasakaH/docs
theme:
  name: "material"
  language: "ja"
  features:
    - content.code.copy
extra:
  search:
    language: "jp"
nav:
  - Home: index.md
  - プログラミング言語:
      - C/C++: Programming/c.md
      - C#: Programming/csharp.md
      - Java: Programming/java.md
      - Kotlin: Programming/kotlin.d
      - ObjectiveC: Programming/objectivec.md
      - Swift: Programming/swift.md
      - Python: Programming/python.md
      - TypeScript: Programming/typescript.md
      - ShellScript: Programming/shellscript.md
  - 開発環境:
      - VSCode: IDE/vscode.md
      - Vim: IDE/vim.md
      - VisualStudio: IDE/visualstudio.md
      - AndroidStudio: IDE/androidstudio.md
      - XCode: IDE/xcode.md
  - サーバー管理:
      - Linuxコマンドメモ: Linux/cmd.md
  - 自動化:
      - GitLabCI: Automation/gitlabci.md
      - GitHubActions: Automation/githubactions.md
      - Jenkins: Automation/jenkins.md
  - コンテナ:
      - 環境構築:
          - WSL2: Container/Development/wsl2.md
          - Docker: Container/Development/docker.md
          - Kubernetes: Container/Development/k8s.md
      - Docker:
          - CLI: Cotainer/Docker/cli.md
          - Dockerfile: Container/Docker/dockerfile.md
          - compose: Container/Docker/compose.md
      - Kubernetes:
          - minikube: Container/Kubernetes/minikube.md
          - kubectl: Container/Kubernetes/kubectl.md
          - Kompose: Container/Kubernetes/kompose.md
  - Web関連:
      - フロントエンド:
          - React:
              - 環境構築: Web/Frontend/React/development.md
          - NextJS:
              - 環境構築: Web/Frontend/NextJS/development.md
          - Angular:
              - 環境構築: Web/Frontend/Angular/development.md
      - バックエンド:
          - Python:
              - FastAPI:
                  - 環境構築: Web/Backend/Python/FastAPI/development.md
          - TypeScript:
              - NestJS:
                  - 環境構築: Web/Backend/TypeScript/NestJS/development.md
              - Express:
                  - 環境構築: Web/Backend/TypeScript/Express/development.md
          - Java:
              - SpringBoot:
                  - 環境構築: Web/Backend/Java/SpringBoot/development.md

  - データベース:
      - RDB:
          - PostgreSQL: Database/RDB/postgresql.md
          - MySQL: Database/RDB/mysql.md
      - NoSQL:
          - MongoDB: Database/NoSQL/mongodb.md
          - ElasticSearch: Database/NoSQL/elasticsearch.md
  - モニタリング:
      - データ収集:
          - Prometheus: Monitoring/DataCollection/prometheus.md
      - 自動通知:
          - AlertManager: Monitoring/Notification/alertmanager.md
      - 可視化:
          - Grafana: Monitoring/Visualization/grafana.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - codehilite:
      noclasses: true
      pygments_style: colorful
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - mdx_truly_sane_lists:
      nested_indent: 2
  - admonition

